CODIGO = "2230532"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.provision "shell", run: "always",
    inline: "ip route del 192.168.50.3 via 10.0.2.2 dev eth0 2>/dev/null || true"

  config.vm.define "srv2" do |s|
    s.vm.hostname = "srv2-#{CODIGO}"
    s.vm.network "private_network", ip: "192.168.50.2", virtualbox__intnet: "red_interna"
    # Ruta de regreso hacia el cliente a traves de srv1
    s.vm.provision "shell", run: "always",
      inline: "ip route replace 192.168.56.0/24 via 192.168.50.3 dev eth1"
    s.vm.provider "virtualbox" do |vb|
      vb.name = "parcial2-srv2"
      vb.memory = 1024
    end
  end

  config.vm.define "srv1" do |s|
    s.vm.hostname = "srv1-#{CODIGO}"
    s.vm.network "private_network", ip: "192.168.56.10"
    s.vm.network "private_network", ip: "192.168.50.3", virtualbox__intnet: "red_interna"
    s.vm.provider "virtualbox" do |vb|
      vb.name = "parcial2-srv1"
      vb.memory = 1024
    end
  end

  config.vm.define "cliente" do |s|
    s.vm.hostname = "cliente-#{CODIGO}"
    s.vm.network "private_network", ip: "192.168.56.20"
    s.vm.provider "virtualbox" do |vb|
      vb.name = "parcial2-cliente"
      vb.memory = 1024
    end
  end
end