# ==========================================
# VSFTPD - SEGUNDO PARCIAL
# FTPS EXPLICITO
# Codigo: 2235621
# ==========================================

listen=YES
listen_ipv6=NO

# --------------------------
# Usuarios locales
# --------------------------
anonymous_enable=NO
local_enable=YES
write_enable=YES

# --------------------------
# Registro
# --------------------------
use_localtime=YES
xferlog_enable=YES

# --------------------------
# Configuracion general
# --------------------------
pam_service_name=vsftpd
secure_chroot_dir=/var/run/vsftpd/empty

# ==========================================
# TLS / FTPS
# ==========================================

ssl_enable=YES

# No permitir TLS para usuarios anonimos
allow_anon_ssl=NO

# Obligar cifrado del login
force_local_logins_ssl=YES

# Obligar cifrado de transferencia de datos
force_local_data_ssl=YES

# TLS habilitado
ssl_tlsv1=YES

# Protocolos antiguos deshabilitados
ssl_sslv2=NO
ssl_sslv3=NO

# Certificado y clave privada
rsa_cert_file=/etc/ssl/certs/servidor.crt
rsa_private_key_file=/etc/ssl/private/servidor.key

# ==========================================
# MODO PASIVO
# ==========================================

pasv_enable=YES

pasv_min_port=50000
pasv_max_port=50010

# Direccion que el cliente debe utilizar
# Corresponde al lado externo de srv1
pasv_address=192.168.60.10
